name: lint

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: run lint
        run: yarn lint
